version: "3"
services:
   service0:
      expose:
         - 5000
      ports:
         - 5000:5000
      environment:
         - VIRTUAL_HOST=${SERVICE_DOMAIN}
         - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
         - VIRTUAL_PORT=5000
         - PORT=5000
      networks:
         - back
         - reverse-proxy
networks:
   reverse-proxy:
      external:
         name: reverse-proxy
   back:
      driver: bridge