version: "3.3"
services:
   kotlinapp:
      container_name: kotlinapp
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "5000:5000"
      environment:
         - VIRTUAL_HOST=${SERVICE_DOMAIN}
         - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
         - VIRTUAL_PORT=5000
         - PORT=5000

