version: "3.3"
services:
   service0:
      container_name: backend_hbe
      build:
         context: ../test-deploy
      ports:
         - "5000:5000"
      environment:
         - VIRTUAL_HOST=${SERVICE_DOMAIN}
         - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
         - VIRTUAL_PORT=5000
         - PORT=5000

