version: "3"
services:
   test-deploy:
      build:
         context: ${TEST_SRC_DIR}
         dockerfile: Dockerfile
      ports:
         - "5000:5000"
      expose:
         - 5000
      environment:
         - VIRTUAL_HOST=${SERVICE_DOMAIN}
         - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
         - VIRTUAL_PORT=5000
         - PORT=5000
      networks:
         - back
         - reverse-proxy
networks:
   reverse-proxy:
      external:
         name: reverse-proxy
   back:
      driver: bridge