version: "3.3"
services:
   kotlinapp:
      container_name: kotlinapp
      build:
         context: .
         dockerfile: Dockerfile
      environment:
         - JAVA_OPTS=-Xmx256m -Xms256m -Djava.awt.headless=true
         - VIRTUAL_HOST=${SERVICE_DOMAIN}
         - LETSENCRYPT_HOST=${SERVICE_DOMAIN}
         - VIRTUAL_PORT=5000
         - PORT=5000

